/*Define que o schema padrao, deve ser mapeado no workspace*/
use dfs.receita_federal;
/*Exibe os arquivos que estão no workspace*/
show files;
/*Configura a gravacao em formato Parquet*/
ALTER SESSION SET `store.format` = 'parquet';

/*Tabela criada em etapa anterior con os registros de CNPJ*/
select * from receita_federal_cnpj;

/*Cria tabela com colunas do layout de CNPJ*/
drop table cnpj_tabulado;

create table cnpj_tabulado as
SELECT
	SUBSTRING(REGISTRO,1,1) INDICADOR_FULL_DIARIO,
	SUBSTRING(REGISTRO,2,1) TIPO_ATUALIZACAO,
	SUBSTRING(REGISTRO,3,14) CNPJ,
	SUBSTRING(REGISTRO,17,1) MATRIZ_FILIAL,
	SUBSTRING(REGISTRO,18,150) RAZAO_SOCIAL,
	SUBSTRING(REGISTRO,168,55) NOME_FANTASIA,
	SUBSTRING(REGISTRO,223,2) SITUACAO_CADASTRAL,
	SUBSTRING(REGISTRO,225,8) DATA_SITUACAO_CADASTRAL,
	SUBSTRING(REGISTRO,233,2) MOTIVO_SITUACAO_CADASTRAL,
	SUBSTRING(REGISTRO,235,55) NOME_CIDADE_EXTERIOR,
	SUBSTRING(REGISTRO,290,3) CODIGO_PAIS,
	SUBSTRING(REGISTRO,293,70) NOME_PAIS,
	SUBSTRING(REGISTRO,363,4) CODIGO_NATUREZA_JURIDICA,
	SUBSTRING(REGISTRO,367,8) DATA_INICIO_ATIVIDADE,
	SUBSTRING(REGISTRO,375,7) CNAE_FISCAL,
	SUBSTRING(REGISTRO,382,20) TIPO_LOGRADOURO,
	SUBSTRING(REGISTRO,402,60) LOGRADOURO,
	SUBSTRING(REGISTRO,462,6) NUMERO,
	SUBSTRING(REGISTRO,468,156) COMPLEMENTO,
	SUBSTRING(REGISTRO,624,50) BAIRRO,
	SUBSTRING(REGISTRO,674,8) CEP,
	SUBSTRING(REGISTRO,682,2) UF,
	SUBSTRING(REGISTRO,684,4) CODIGO_MUNICIPIO,
	SUBSTRING(REGISTRO,688,50) MUNICIPIO,
	SUBSTRING(REGISTRO,738,12) DDD_TELEFONE_1,
	SUBSTRING(REGISTRO,738,4) DDD_1,
	SUBSTRING(REGISTRO,742,8) TELEFONE_1,
	SUBSTRING(REGISTRO,750,12) DDD_TELEFONE_2,
	SUBSTRING(REGISTRO,750,4) DDD_2,
	SUBSTRING(REGISTRO,754,8) TELEFONE_2,
	SUBSTRING(REGISTRO,762,12) DDD_FAX_3,
	SUBSTRING(REGISTRO,762,4) DDD_3,
	SUBSTRING(REGISTRO,766,8) FAX_3,
	SUBSTRING(REGISTRO,774,115) EMAIL,
	SUBSTRING(REGISTRO,889,2) QUALIFICACAO_RESPONSAVEL,
	SUBSTRING(REGISTRO,891,14) CAPITAL_SOCIAL,
	SUBSTRING(REGISTRO,905,2) PORTE_EMPRESA,
	SUBSTRING(REGISTRO,907,1) OPCAO_SIMPLES,
	SUBSTRING(REGISTRO,908,8) DATA_OPCAO_SIMPLES,
	SUBSTRING(REGISTRO,916,8) DATA_EXCLUSAO_SIMPLES,
	SUBSTRING(REGISTRO,924,1) OPCAO_MEI,
	SUBSTRING(REGISTRO,925,23) SITUACAO_ESPECIAL,
	SUBSTRING(REGISTRO,948,8) DATA_SITUACAO_ESPECIAL,
	SUBSTRING(REGISTRO,956,243) FILLER,
	SUBSTRING(REGISTRO,1199,1) FIM_REGISTRO
FROM receita_federal_cnpj;

select * from cnpj_tabulado;


SELECT
	SUBSTRING(REGISTRO,1,1) INDICADOR_FULL_DIARIO,
	REGISTRO
FROM receita_federal_socio;

select * from receita_federal_socio;

select * from receita_federal_cnae;

